// This file is generated by the corba.js IDL compiler from 'corba/interface/interface.idl'.

#pragma once
#include <corba/corba.hh>
#include <corba/orb.hh>
#include <corba/giop.hh>
#include <corba/coroutine.hh>
#include <vector>
#include "interface.hh"

class Peer_skel: public CORBA::Skeleton, public Peer {
public:
    Peer_skel(std::shared_ptr<CORBA::ORB> orb) : Skeleton(orb) {}
private:
    CORBA::async<> _call(const std::string_view &operation, CORBA::GIOPDecoder &decoder, CORBA::GIOPEncoder &encoder) override;
};

class Interface_skel: public CORBA::Skeleton, public Interface {
public:
    Interface_skel(std::shared_ptr<CORBA::ORB> orb) : Skeleton(orb) {}
private:
    CORBA::async<> _call(const std::string_view &operation, CORBA::GIOPDecoder &decoder, CORBA::GIOPEncoder &encoder) override;
};

